name: "🧙 Shard Request"
description: Create a new ticket for adding your shard to the server list
title: "🧙 [Shard Request] - <shard name>"
labels: [
  "shard-request"
]
assignees:
  - jabinb
body:
  - type: markdown
    attributes:
      value: |
        Enter your shard details below, we'll do our best to add it as soon as we can.
        If you have issues/questions please contact us directly via the CUO discord.
        
        :warning: We're currently taking limited shard applications while we automate the shard registration, expect delays :warning:
  - type: input
    id: shard-name
    attributes:
      label: Shard Name
    validations:
      required: true
  - type: input
    id: shard-contact
    attributes:
      label: Shard admins
      description: Please provide the Discord usernames of people responsible for your shard
      placeholder: e.g. `karasho` `blank000` etc
    validations:
      required: false
  - type: textarea
    id: shard-description
    attributes:
      label: Shard description
      description: A brief 2-3 sentence description of why you want to add your shard to the web client
    validations:
      required: true
  - type: dropdown
    id: shard-phase
    attributes:
      label: Shard phase
      description: What state is your shard in, is it launched?
      multiple: true
      options:
        - Development
        - Testing (Pre-Live)
        - Live
    validations:
      required: true
  - type: dropdown
    id: shard-pop
    attributes:
      label: Shard population
      description: What is the average concurrent players of your shard
      multiple: true
      options:
        - 0-10
        - 10-100
        - 100+
    validations:
      required: true
  - type: textarea
    id: shard-comments
    attributes:
      label: Comments/Requests
      description: If you have any extra comments/requests place them here
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to be patient and acknowledge that the CUO devs are working on their own free time to help me.
          required: true
