name: Publish

on:
  push:
    branches: [ main ]

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup nodejs 21
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Setup yarn
        id: setup-yarn
        shell: bash
        run: |
          corepack enable
          yarn set version 3.2.0

      - name: Build site
        run: |
          yarn install
          yarn docs:build

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages deploy --commit-dirty --branch main --project-name=web-classicuo ./site/.vitepress/dist
